[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build:packages && npm run build:web"

[deploy]
startCommand = "npx serve -s apps/web/dist -l 3000"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
numReplicas = 1

[environment]
# These will be injected at build time
VITE_API_URL = "${{API_URL}}/api"
VITE_SOLANA_NETWORK = "${{SOLANA_NETWORK}}"
VITE_SOLANA_RPC_URL = "${{SOLANA_RPC_URL}}"

[networking]
serviceName = "web"