[build]
builder = "DOCKERFILE"
dockerfilePath = "apps/web/Dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
numReplicas = 1

[environment]
# These will be injected at build time
VITE_API_URL = "${{API_URL}}/api"
VITE_SOLANA_NETWORK = "${{SOLANA_NETWORK}}"
VITE_SOLANA_RPC_URL = "${{SOLANA_RPC_URL}}"

[networking]
serviceName = "web"