# Nixpacks configuration for Railway deployment

[phases.setup]
nixPkgs = ['nodejs_20', 'yarn']

[phases.install]
cmds = [
  'yarn install --frozen-lockfile',
]

[phases.build]
cmds = [
  'yarn workspace @reward-system/config build',
  'yarn workspace @reward-system/shared build',
  'yarn workspace @reward-system/api build',
]

[start]
cmd = 'yarn workspace @reward-system/api start'