# Nixpacks configuration for Railway deployment

[phases.setup]
nixPkgs = ['nodejs_20', 'npm']

[phases.install]
cmds = [
  'npm ci --include=dev',
]

[phases.build]
cmds = [
  'npm run build:packages',
  'npm run build:api',
  'npm run build:web',
]

[start]
cmd = 'npm run start --workspace=apps/api'