[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build:packages && npm run build:api"

[deploy]
startCommand = "npm run start --workspace=apps/api"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
numReplicas = 1

[environment]
NODE_ENV = "production"
PORT = "$PORT"

[networking]
serviceName = "api"